services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
    container_name: flask-api
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    container_name: streamlit-app
    ports:
      - "8501:8501"
    depends_on:
      - backend

volumes:
  mongo_data:
